image: node:24

stages:
  - build

build:
  rules:
    # 允许手动触发
    - if: '$CI_PIPELINE_SOURCE == "web"'
      when: always

    # 允许定时任务触发
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
      when: always

    # 其它情况不触发（如 push）
    - when: never
  
  stage: build
  before_script:
    - apt-get update -qq && apt-get install -y --no-install-recommends rsync
  script:
    - sh scripts/build.sh
    - tar -czf public.tar.gz quartz/public
  artifacts:
    paths:
      - public.tar.gz
    expire_in: 2 hours