image: node:24

stages:
  - build

build:
  stage: build
  before_script:
    - apt-get update -qq && apt-get install -y --no-install-recommends rsync
  script:
    - sh scripts/build.sh
    - tar -czf public.tar.gz quartz/public
  artifacts:
    paths:
      - public.tar.gz
    expire_in: 1 day